import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "3xl": "2560px", // 2K screen support
    },
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#394857",
        "on-primary-container": "#799dd6",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#d8885c",
        "on-surface": "#191c1d",
        secondary: "#50606f",
        "tertiary-fixed": "#ffdbca",
        outline: "#737780",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed": "#0d1d2a",
        "on-tertiary-fixed": "#341100",
        background: "#f8f9fa",
        "inverse-primary": "#a7c8ff",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        error: "#ba1a1a",
        "surface-container": "#edeeef",
        "tertiary-container": "#592300",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-fixed-variant": "#723610",
        "tertiary-fixed-dim": "#ffb690",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed-dim": "#a7c8ff",
        "surface-bright": "#f8f9fa",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d5e3ff",
        primary: "#001e40",
        tertiary: "#381300",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#1f477b",
        "inverse-surface": "#2e3132",
        "primary-container": "#003366",
        "on-secondary-container": "#556474",
        "surface-tint": "#3a5f94",
        "on-primary-fixed": "#001b3c",
        "surface-container-highest": "#e1e3e4",
        "outline-variant": "#c3c6d1",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d4e4f6",
        surface: "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#43474f",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d1e1f4",
        "secondary-fixed-dim": "#b8c8da",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        unit: "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-max-width": "1200px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-lg": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "label-md": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "headline-lg-mobile": ["Public Sans"],
        "label-bold": ["Public Sans"],
        "body-sm": ["Public Sans"],
        "headline-sm": ["Public Sans"],
        "body-md": ["Public Sans"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "label-bold": [
          "12px",
          {
            lineHeight: "1",
            letterSpacing: "0.05em",
            fontWeight: "700",
          },
        ],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
